"""initial smartnotify schema

Revision ID: 4650f6f3d10b
Revises: 
Create Date: 2026-09-29 23:57:41.708545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4650f6f3d10b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('audience_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audience_id'), 'audience', ['id'], unique=False)
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('template_type', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_id'), 'template', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('fcm_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audience_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audience_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audience_id'], ['audience.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audience_id', 'user_id', name='uq_audience_member')
    )
    op.create_index(op.f('ix_audience_members_audience_id'), 'audience_members', ['audience_id'], unique=False)
    op.create_index(op.f('ix_audience_members_id'), 'audience_members', ['id'], unique=False)
    op.create_index(op.f('ix_audience_members_user_id'), 'audience_members', ['user_id'], unique=False)
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(), nullable=False),
    sa.Column('campaign_type', sa.String(length=100), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('audience_id', sa.Integer(), nullable=True),
    sa.Column('schedule_time', sa.DateTime(), nullable=True),
    sa.Column('schedule_frequency', sa.String(length=30), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['audience_id'], ['audience.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_id'), 'campaign', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_next_run_at'), 'campaign', ['next_run_at'], unique=False)
    op.create_table('fcm_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'token', name='uq_fcm_token_user_token')
    )
    op.create_index(op.f('ix_fcm_tokens_id'), 'fcm_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_fcm_tokens_token'), 'fcm_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_fcm_tokens_user_id'), 'fcm_tokens', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=100), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('tracking_token', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_campaign_id'), 'deliveries', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_deliveries_channel'), 'deliveries', ['channel'], unique=False)
    op.create_index(op.f('ix_deliveries_clicked_at'), 'deliveries', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_deliveries_id'), 'deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_deliveries_next_retry_at'), 'deliveries', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_deliveries_opened_at'), 'deliveries', ['opened_at'], unique=False)
    op.create_index(op.f('ix_deliveries_provider_message_id'), 'deliveries', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_deliveries_status'), 'deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_deliveries_tracking_token'), 'deliveries', ['tracking_token'], unique=False)
    op.create_index('ix_delivery_campaign_status', 'deliveries', ['campaign_id', 'status'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=30), server_default='English', nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.String(length=30), nullable=True),
    sa.Column('sentiment_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_campaign_id'), 'feedback', ['campaign_id'], unique=False)
    op.create_index('ix_feedback_campaign_sentiment', 'feedback', ['campaign_id', 'sentiment'], unique=False)
    op.create_index(op.f('ix_feedback_channel'), 'feedback', ['channel'], unique=False)
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_delivery_id'), 'feedback', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_language'), 'feedback', ['language'], unique=False)
    op.create_index(op.f('ix_feedback_sentiment'), 'feedback', ['sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_sentiment'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_language'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_delivery_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_channel'), table_name='feedback')
    op.drop_index('ix_feedback_campaign_sentiment', table_name='feedback')
    op.drop_index(op.f('ix_feedback_campaign_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_delivery_campaign_status', table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_tracking_token'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_status'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_provider_message_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_opened_at'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_next_retry_at'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_clicked_at'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_channel'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_campaign_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_fcm_tokens_user_id'), table_name='fcm_tokens')
    op.drop_index(op.f('ix_fcm_tokens_token'), table_name='fcm_tokens')
    op.drop_index(op.f('ix_fcm_tokens_id'), table_name='fcm_tokens')
    op.drop_table('fcm_tokens')
    op.drop_index(op.f('ix_campaign_next_run_at'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_id'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_audience_members_user_id'), table_name='audience_members')
    op.drop_index(op.f('ix_audience_members_id'), table_name='audience_members')
    op.drop_index(op.f('ix_audience_members_audience_id'), table_name='audience_members')
    op.drop_table('audience_members')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_template_id'), table_name='template')
    op.drop_table('template')
    op.drop_index(op.f('ix_audience_id'), table_name='audience')
    op.drop_table('audience')
    # ### end Alembic commands ###
