"""add email engagement tracking

Revision ID: a296ef8a6ab3
Revises: 5b8c7d9e2a11
Create Date: 2026-08-22 20:09:36.453953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a296ef8a6ab3'
down_revision: Union[str, Sequence[str], None] = '5b8c7d9e2a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_column('audience', 'district')
    op.create_index(op.f('ix_campaign_next_run_at'), 'campaign', ['next_run_at'], unique=False)
    op.add_column('deliveries', sa.Column('tracking_token', sa.String(length=128), nullable=True))
    op.add_column('deliveries', sa.Column('opened_at', sa.DateTime(), nullable=True))
    op.add_column('deliveries', sa.Column('clicked_at', sa.DateTime(), nullable=True))
    op.add_column(
    'deliveries',
    sa.Column(
        'click_count',
        sa.Integer(),
        nullable=False,
        server_default='0'
    )
)
    op.create_index(op.f('ix_deliveries_channel'), 'deliveries', ['channel'], unique=False)
    op.create_index(op.f('ix_deliveries_clicked_at'), 'deliveries', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_deliveries_opened_at'), 'deliveries', ['opened_at'], unique=False)
    op.create_index(op.f('ix_deliveries_provider_message_id'), 'deliveries', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_deliveries_status'), 'deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_deliveries_tracking_token'), 'deliveries', ['tracking_token'], unique=False)
    op.create_index('ix_delivery_campaign_status', 'deliveries', ['campaign_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_delivery_campaign_status', table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_tracking_token'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_status'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_provider_message_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_opened_at'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_clicked_at'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_channel'), table_name='deliveries')
    op.drop_column('deliveries', 'click_count')
    op.drop_column('deliveries', 'clicked_at')
    op.drop_column('deliveries', 'opened_at')
    op.drop_column('deliveries', 'tracking_token')
    op.drop_index(op.f('ix_campaign_next_run_at'), table_name='campaign')
    op.add_column('audience', sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###
